apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: make-vet-appointment
spec:
  template:
    spec:
      containers:
        - image: ko://knative-composition/vetappointment/cmd/makeAppointment
